# Generated by Django 4.2.2 on 2024-09-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_milage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milage',
            old_name='mileage',
            new_name='milage',
        ),
    ]
